Rem ------ -------- -------- -------- -------- ------- -------- ------- 
Rem TCP/IP Varbiles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem IP Address
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set IP1=1
    Set IP2=5
    Set IP3=5
    Set IP4=1
    Set IP5=0
    Set IP6=8
    Set IP7=0
    Set IP8=6
    Set IP9=9
    Set IP10=2
    Set IP11=3
    Set IP12=1
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Gateway
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set GW1=1
    Set GW2=5
    Set GW3=5
    Set GW4=1
    Set GW5=0
    Set GW6=8
    Set GW7=0
    Set GW8=6
    Set GW9=9
    Set GW10=2
    Set GW11=5
    Set GW12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Building WIN's Servers Are In
  Rem ----------------------------------------------------------------
    Set BUILDING=Adams
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Primary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PW1=1
    Set PW2=5
    Set PW3=5
    Set PW4=1
    Set PW5=0
    Set PW6=8
    Set PW7=1
    Set PW8=5
    Set PW9=2
    Set PW10=1
    Set PW11=0
    Set PW12=5
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Secondary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SW1=1
    Set SW2=5
    Set SW3=5
    Set SW4=1
    Set SW5=0
    Set SW6=8
    Set SW7=0
    Set SW8=4
    Set SW9=3
    Set SW10=0
    Set SW11=5
    Set SW12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem SubNet Mask
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SM1=2
    Set SM2=5
    Set SM3=5
    Set SM4=2
    Set SM5=5
    Set SM6=5
    Set SM7=2
    Set SM8=5
    Set SM9=5
    Set SM10=0
    Set SM11=0
    Set SM12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PDC Or A BDC'S IP Address
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PB1=1
    Set PB2=5
    Set PB3=5
    Set PB4=1
    Set PB5=0
    Set PB6=8
    Set PB7=2
    Set PB8=1
    Set PB9=8
    Set PB10=1
    Set PB11=8
    Set PB12=1
 
Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Logan Varibles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Username
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set UN1=C
    Set UN2=U
    Set UN3=M
    Set UN4=M
    Set UN5=I
    Set UN6=J
    Set UN7=H
    Set UN8= 
    Set UN9= 
    Set UN10= 
    Set UN11= 
    Set UN12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Password
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PS1= 
    Set PS2= 
    Set PS3= 
    Set PS4= 
    Set PS5= 
    Set PS6= 
    Set PS7= 
    Set PS8= 
    Set PS9= 
    Set PS10= 
    Set PS11= 
    Set PS12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PC Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PN1=B
    Set PN2=O
    Set PN3=O
    Set PN4=T
    Set PN5=D
    Set PN6=I
    Set PN7=S
    Set PN8=K
    Set PN9= 
    Set PN10= 
    Set PN11= 
    Set PN12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set DM1=N
    Set DM2=_
    Set DM3=A
    Set DM4=M
    Set DM5=E
    Set DM6=R
    Set DM7=I
    Set DM8=C
    Set DM9=A
    Set DM10=
    Set DM11=
    Set DM12=
