Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display TCP/IP Window
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISCOL00 OFF RED BLACK
  Echo [4;8Hึฤ
  Call DISCOL00 ON WHITE BLUE
  Echo [4;10H            TCP/IP           
  Call DISCOL00 OFF RED BLACK
  Echo [4;39Hฤท
  Echo [5;8Hบ                               บ 
  Echo [6;8Hบ                               บ 
  Echo [7;8Hบ                               บ 
  Echo [8;8Hบ                               บ 
  Echo [9;8Hบ                               บ 
  Echo [10;8Hบ                               บ 
  Echo [11;8Hบ                               บ 
  Echo [12;8Hศอออออออออออออออออออออออออออออออผ 
  Echo [13;10H                               
