Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Change Window
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISCOL00 OFF RED BLACK
  Echo [4;52Hึฤ
  Call DISCOL00 ON WHITE BLUE
  Echo [4;54H      Change     
  Call DISCOL00 OFF RED BLACK
  Echo [4;71Hฤท
  Echo [5;52Hบ                   บ 
  Echo [6;52Hบ                   บ 
  Echo [7;52Hบ                   บ 
  Echo [8;52Hบ                   บ 
  Echo [9;52Hบ                   บ 
  Echo [10;52Hบ                   บ 
  Echo [11;52Hบ                   บ 
  Echo [12;52Hบ                   บ 
  Echo [13;52Hบ                   บ 
  Echo [14;52Hบ                   บ 
  Echo [15;52Hบ                   บ 
  Echo [16;52Hศอออออออออออออออออออผ 
  Echo [17;53H                    
