Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display NIC Window
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISCOL00 OFF RED BLACK
  Echo [3;3Hึฤ
  Call DISCOL00 ON WHITE BLUE
  Echo [3;5H        Availaible NIC's          
  Call DISCOL00 OFF RED BLACK
  Echo [3;38Hฤท
  Echo [4;3Hบ                                   บ 
  Echo [5;3Hบ                                   บ 
  Echo [6;3Hบ                                   บ 
  Echo [7;3Hบ                                   บ 
  Echo [8;3Hบ                                   บ 
  Echo [9;3Hบ                                   บ 
  Echo [10;3Hบ                                   บ 
  Echo [11;3Hบ                                   บ 
  Echo [12;3Hบ                                   บ 
  Echo [13;3Hบ                                   บ 
  Echo [14;3Hบ                                   บ 
  Echo [15;3Hบ                                   บ 
  Echo [16;3Hบ                                   บ 
  Echo [17;3Hบ                                   บ 
  Echo [18;3Hบ                                   บ 
  Echo [19;3Hบ                                   บ 
  Echo [20;3Hบ                                   บ 
  Echo [21;3Hศอออออออออออออออออออออออออออออออออออผ 
  Echo [22;4H                                    

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Status Window
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISCOL00 OFF RED BLACK
  Echo [3;50Hึฤ
  Call DISCOL00 ON WHITE BLUE
  Echo [3;52H          Status        
  Call DISCOL00 OFF RED BLACK
  Echo [3;76Hฤท
  Echo [4;50Hบ Couldn't determine NIC.  บ 
  Echo [5;50Hบ To add a driver contact  บ 
  Echo [6;50Hบ Peter Evans              บ 
  Echo [7;50Hบ 617-985-1744             บ 
  Echo [8;50Hบ pmevans@statestreet.com  บ 
  Echo [9;50Hบ                          บ 
  Echo [10;50Hบ                          บ 
  Echo [11;50Hบ                          บ 
  Echo [12;50Hบ                          บ 
  Echo [13;50Hบ                          บ 
  Echo [14;50Hบ ESC-Exit                 บ 
  Echo [15;50Hศออออออออออออออออออออออออออผ 
  Echo [16;51H                           
