Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display TCP/IP, Logon and Change Windows
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISSCR01
  Call DISSCR02
  Call DISSCR03

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Action Window And Actions
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISSCR04
