Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Logon Window
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call DISCOL00 OFF RED BLACK
  Echo [16;8Hึฤ
  Call DISCOL00 ON WHITE BLUE
  Echo [16;10H            Logon            
  Call DISCOL00 OFF RED BLACK
  Echo [16;39Hฤท
  Echo [17;8Hบ                               บ 
  Echo [18;8Hบ                               บ 
  Echo [19;8Hบ                               บ 
  Echo [20;8Hบ                               บ 
  Echo [21;8Hบ                               บ 
  Echo [22;8Hศอออออออออออออออออออออออออออออออผ 
  Echo [23;9H                                
