Rem ------ -------- -------- -------- -------- ------- -------- ------- 
Rem TCP/IP Varbiles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem IP Address
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set IP1=1
    Set IP2=9
    Set IP3=2
    Set IP4=1
    Set IP5=6
    Set IP6=8
    Set IP7=0
    Set IP8=0
    Set IP9=1
    Set IP10=0
    Set IP11=1
    Set IP12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Gateway
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set GW1=0
    Set GW2=0
    Set GW3=0
    Set GW4=0
    Set GW5=0
    Set GW6=0
    Set GW7=0
    Set GW8=0
    Set GW9=0
    Set GW10=0
    Set GW11=0
    Set GW12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Building WIN's Servers Are In
  Rem ----------------------------------------------------------------
    Set BUILDING=Willard
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Primary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PW1=0
    Set PW2=0
    Set PW3=0
    Set PW4=0
    Set PW5=0
    Set PW6=0
    Set PW7=0
    Set PW8=0
    Set PW9=0
    Set PW10=0
    Set PW11=0
    Set PW12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Secondary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SW1=0
    Set SW2=0
    Set SW3=0
    Set SW4=0
    Set SW5=0
    Set SW6=0
    Set SW7=0
    Set SW8=0
    Set SW9=0
    Set SW10=0
    Set SW11=0
    Set SW12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem SubNet Mask
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SM1=2
    Set SM2=5
    Set SM3=5
    Set SM4=2
    Set SM5=5
    Set SM6=5
    Set SM7=2
    Set SM8=5
    Set SM9=5
    Set SM10=0
    Set SM11=0
    Set SM12=0
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PDC Or A BDC'S IP Address
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PB1=1
    Set PB2=9
    Set PB3=2
    Set PB4=1
    Set PB5=6
    Set PB6=8
    Set PB7=0
    Set PB8=0
    Set PB9=1
    Set PB10=0
    Set PB11=1
    Set PB12=0
 
Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Logan Varibles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Username
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set UN1=T
    Set UN2=E
    Set UN3=S
    Set UN4=T
    Set UN5=E
    Set UN6=R
    Set UN7= 
    Set UN8= 
    Set UN9= 
    Set UN10= 
    Set UN11= 
    Set UN12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Password
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PS1= 
    Set PS2= 
    Set PS3= 
    Set PS4= 
    Set PS5= 
    Set PS6= 
    Set PS7= 
    Set PS8= 
    Set PS9= 
    Set PS10= 
    Set PS11= 
    Set PS12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PC Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PN1=B
    Set PN2=O
    Set PN3=O
    Set PN4=T
    Set PN5=D
    Set PN6=I
    Set PN7=S
    Set PN8=K
    Set PN9= 
    Set PN10= 
    Set PN11= 
    Set PN12= 
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set DM1=N
    Set DM2=T
    Set DM3=D
    Set DM4=O
    Set DM5=M
    Set DM6=A
    Set DM7=I
    Set DM8=N
    Set DM9= 
    Set DM10= 
    Set DM11= 
    Set DM12= 
