Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Used Exclusivly Within DISCOL00
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set FOREGROUND=
  Set BACKGROUND=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Represents Highlighted Item On Main Menu (1=1st Item, 2=2nd Item, etc.)
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set ITEMHIGH=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Represents Highlighted Item On Building Menu (1=1st Item, 2=2nd Item, etc.)
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set BITEMHIGH=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Represents Highlighted Item On NIC Menu (1=1st Item, 2=2nd Item, etc.)
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set DITEMHIGH=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Window Which Highlighter Is In (TCP=TCP/IP Window, LOG=LOGON Window)
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set AWINDOW=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Used Exclusivly Within In EDIITE00
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set POSITION=
  Set CH1=
  Set CH2=
  Set CH3=
  Set CH4=
  Set CH5=
  Set CH6=
  Set CH7=
  Set CH8=
  Set CH9=
  Set CH10=
  Set CH11=
  Set CH12=
  Set WFUI=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Set To 0 Before A Routine Acting Upon A Key Returns. This Method
Rem Aids In Input Loop Creation Via CHOICE.COM
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set WFUI=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Set To F10 Or ESC If Pressed. All Parent Routines Must Check For
Rem This After Receiving Control Back From A Routine That Gets Input
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set ACTION=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem NIC Name Displayed On Screen
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set NICNAME=

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem NIC Name Displayed On Screen
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set NICTYPE=

