Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Overwrite INTVAR01 File With New Values. Thus Saving The Values To
Rem Disk Enalding Them To Be Loaded During Next Boot
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Echo Rem ------ -------- -------- -------- -------- ------- -------- ------- > INTVAR01.BAT
  Echo Rem TCP/IP Varbiles>> INTVAR01.BAT
  Echo Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem IP Address>> INTVAR01.BAT
  Echo   Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo     Set IP1=%IP1%>> INTVAR01.BAT
  Echo     Set IP2=%IP2%>> INTVAR01.BAT
  Echo     Set IP3=%IP3%>> INTVAR01.BAT
  Echo     Set IP4=%IP4%>> INTVAR01.BAT
  Echo     Set IP5=%IP5%>> INTVAR01.BAT
  Echo     Set IP6=%IP6%>> INTVAR01.BAT
  Echo     Set IP7=%IP7%>> INTVAR01.BAT
  Echo     Set IP8=%IP8%>> INTVAR01.BAT
  Echo     Set IP9=%IP9%>> INTVAR01.BAT
  Echo     Set IP10=%IP10%>> INTVAR01.BAT
  Echo     Set IP11=%IP11%>> INTVAR01.BAT
  Echo     Set IP12=%IP12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Gateway>> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo     Set GW1=%GW1%>> INTVAR01.BAT
  Echo     Set GW2=%GW2%>> INTVAR01.BAT
  Echo     Set GW3=%GW3%>> INTVAR01.BAT
  Echo     Set GW4=%GW4%>> INTVAR01.BAT
  Echo     Set GW5=%GW5%>> INTVAR01.BAT
  Echo     Set GW6=%GW6%>> INTVAR01.BAT
  Echo     Set GW7=%GW7%>> INTVAR01.BAT
  Echo     Set GW8=%GW8%>> INTVAR01.BAT
  Echo     Set GW9=%GW9%>> INTVAR01.BAT
  Echo     Set GW10=%GW10%>> INTVAR01.BAT
  Echo     Set GW11=%GW11%>> INTVAR01.BAT
  Echo     Set GW12=%GW12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Building WIN's Servers Are In>> INTVAR01.BAT
  Echo   Rem ---------------------------------------------------------------->> INTVAR01.BAT
  Echo     Set BUILDING=%BUILDING%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Primary WINS Server>> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo     Set PW1=%PW1%>> INTVAR01.BAT
  Echo     Set PW2=%PW2%>> INTVAR01.BAT
  Echo     Set PW3=%PW3%>> INTVAR01.BAT
  Echo     Set PW4=%PW4%>> INTVAR01.BAT
  Echo     Set PW5=%PW5%>> INTVAR01.BAT
  Echo     Set PW6=%PW6%>> INTVAR01.BAT
  Echo     Set PW7=%PW7%>> INTVAR01.BAT
  Echo     Set PW8=%PW8%>> INTVAR01.BAT
  Echo     Set PW9=%PW9%>> INTVAR01.BAT
  Echo     Set PW10=%PW10%>> INTVAR01.BAT
  Echo     Set PW11=%PW11%>> INTVAR01.BAT
  Echo     Set PW12=%PW12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Secondary WINS Server>> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo     Set SW1=%SW1%>> INTVAR01.BAT
  Echo     Set SW2=%SW2%>> INTVAR01.BAT
  Echo     Set SW3=%SW3%>> INTVAR01.BAT
  Echo     Set SW4=%SW4%>> INTVAR01.BAT
  Echo     Set SW5=%SW5%>> INTVAR01.BAT
  Echo     Set SW6=%SW6%>> INTVAR01.BAT
  Echo     Set SW7=%SW7%>> INTVAR01.BAT
  Echo     Set SW8=%SW8%>> INTVAR01.BAT
  Echo     Set SW9=%SW9%>> INTVAR01.BAT
  Echo     Set SW10=%SW10%>> INTVAR01.BAT
  Echo     Set SW11=%SW11%>> INTVAR01.BAT
  Echo     Set SW12=%SW12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem SubNet Mask>> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo     Set SM1=%SM1%>> INTVAR01.BAT
  Echo     Set SM2=%SM2%>> INTVAR01.BAT
  Echo     Set SM3=%SM3%>> INTVAR01.BAT
  Echo     Set SM4=%SM4%>> INTVAR01.BAT
  Echo     Set SM5=%SM5%>> INTVAR01.BAT
  Echo     Set SM6=%SM6%>> INTVAR01.BAT
  Echo     Set SM7=%SM7%>> INTVAR01.BAT
  Echo     Set SM8=%SM8%>> INTVAR01.BAT
  Echo     Set SM9=%SM9%>> INTVAR01.BAT
  Echo     Set SM10=%SM10%>> INTVAR01.BAT
  Echo     Set SM11=%SM11%>> INTVAR01.BAT
  Echo     Set SM12=%SM12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem PDC Or A BDC'S IP Address>> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo     Set PB1=%PB1%>> INTVAR01.BAT
  Echo     Set PB2=%PB2%>> INTVAR01.BAT
  Echo     Set PB3=%PB3%>> INTVAR01.BAT
  Echo     Set PB4=%PB4%>> INTVAR01.BAT
  Echo     Set PB5=%PB5%>> INTVAR01.BAT
  Echo     Set PB6=%PB6%>> INTVAR01.BAT
  Echo     Set PB7=%PB7%>> INTVAR01.BAT
  Echo     Set PB8=%PB8%>> INTVAR01.BAT
  Echo     Set PB9=%PB9%>> INTVAR01.BAT
  Echo     Set PB10=%PB10%>> INTVAR01.BAT
  Echo     Set PB11=%PB11%>> INTVAR01.BAT
  Echo     Set PB12=%PB12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo Rem Logan Varibles>> INTVAR01.BAT
  Echo Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Domain Username>> INTVAR01.BAT
  Echo   Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo     Set UN1=%UN1%>> INTVAR01.BAT
  Echo     Set UN2=%UN2%>> INTVAR01.BAT
  Echo     Set UN3=%UN3%>> INTVAR01.BAT
  Echo     Set UN4=%UN4%>> INTVAR01.BAT
  Echo     Set UN5=%UN5%>> INTVAR01.BAT
  Echo     Set UN6=%UN6%>> INTVAR01.BAT
  Echo     Set UN7=%UN7%>> INTVAR01.BAT
  Echo     Set UN8=%UN8%>> INTVAR01.BAT
  Echo     Set UN9=%UN9%>> INTVAR01.BAT
  Echo     Set UN10=%UN10%>> INTVAR01.BAT
  Echo     Set UN11=%UN11%>> INTVAR01.BAT
  Echo     Set UN12=%UN12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Domain Password>> INTVAR01.BAT
  Echo   Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo     Set PS1=%PS1%>> INTVAR01.BAT
  Echo     Set PS2=%PS2%>> INTVAR01.BAT
  Echo     Set PS3=%PS3%>> INTVAR01.BAT
  Echo     Set PS4=%PS4%>> INTVAR01.BAT
  Echo     Set PS5=%PS5%>> INTVAR01.BAT
  Echo     Set PS6=%PS6%>> INTVAR01.BAT
  Echo     Set PS7=%PS7%>> INTVAR01.BAT
  Echo     Set PS8=%PS8%>> INTVAR01.BAT
  Echo     Set PS9=%PS9%>> INTVAR01.BAT
  Echo     Set PS10=%PS10%>> INTVAR01.BAT
  Echo     Set PS11=%PS11%>> INTVAR01.BAT
  Echo     Set PS12=%PS12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem PC Name>> INTVAR01.BAT
  Echo   Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo     Set PN1=%PN1%>> INTVAR01.BAT
  Echo     Set PN2=%PN2%>> INTVAR01.BAT
  Echo     Set PN3=%PN3%>> INTVAR01.BAT
  Echo     Set PN4=%PN4%>> INTVAR01.BAT
  Echo     Set PN5=%PN5%>> INTVAR01.BAT
  Echo     Set PN6=%PN6%>> INTVAR01.BAT
  Echo     Set PN7=%PN7%>> INTVAR01.BAT
  Echo     Set PN8=%PN8%>> INTVAR01.BAT
  Echo     Set PN9=%PN9%>> INTVAR01.BAT
  Echo     Set PN10=%PN10%>> INTVAR01.BAT
  Echo     Set PN11=%PN11%>> INTVAR01.BAT
  Echo     Set PN12=%PN12%>> INTVAR01.BAT
  Echo. >> INTVAR01.BAT
  Echo   Rem ------ -------- -------- -------- -------- ------- -------- ------->> INTVAR01.BAT
  Echo   Rem Domain Name>> INTVAR01.BAT
  Echo   Rem ---------- -------- -------- -------- -------- ------- -------- --->> INTVAR01.BAT
  Echo     Set DM1=%DM1%>> INTVAR01.BAT
  Echo     Set DM2=%DM2%>> INTVAR01.BAT
  Echo     Set DM3=%DM3%>> INTVAR01.BAT
  Echo     Set DM4=%DM4%>> INTVAR01.BAT
  Echo     Set DM5=%DM5%>> INTVAR01.BAT
  Echo     Set DM6=%DM6%>> INTVAR01.BAT
  Echo     Set DM7=%DM7%>> INTVAR01.BAT
  Echo     Set DM8=%DM8%>> INTVAR01.BAT
  Echo     Set DM9=%DM9%>> INTVAR01.BAT
  Echo     Set DM10=%DM10%>> INTVAR01.BAT
  Echo     Set DM11=%DM11%>> INTVAR01.BAT
  Echo     Set DM12=%DM12%>> INTVAR01.BAT
