Rem ------ -------- -------- -------- -------- ------- -------- ------- 
Rem TCP/IP Varbiles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem IP Address
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set IP1=
    Set IP2=
    Set IP3=
    Set IP4=
    Set IP5=
    Set IP6=
    Set IP7=
    Set IP8=
    Set IP9=
    Set IP10=
    Set IP11=
    Set IP12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Gateway
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set GW1=
    Set GW2=
    Set GW3=
    Set GW4=
    Set GW5=
    Set GW6=
    Set GW7=
    Set GW8=
    Set GW9=
    Set GW10=
    Set GW11=
    Set GW12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Building WIN's Servers Are In
  Rem ----------------------------------------------------------------
    Set BUILDING=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Primary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PW1=
    Set PW2=
    Set PW3=
    Set PW4=
    Set PW5=
    Set PW6=
    Set PW7=
    Set PW8=
    Set PW9=
    Set PW10=
    Set PW11=
    Set PW12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Secondary WINS Server
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SW1=
    Set SW2=
    Set SW3=
    Set SW4=
    Set SW5=
    Set SW6=
    Set SW7=
    Set SW8=
    Set SW9=
    Set SW10=
    Set SW11=
    Set SW12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem SubNet Mask
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set SM1=
    Set SM2=
    Set SM3=
    Set SM4=
    Set SM5=
    Set SM6=
    Set SM7=
    Set SM8=
    Set SM9=
    Set SM10=
    Set SM11=
    Set SM12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PDC Or A BDC'S IP Address
  Rem ------ -------- -------- -------- -------- ------- -------- -------
    Set PB1=
    Set PB2=
    Set PB3=
    Set PB4=
    Set PB5=
    Set PB6=
    Set PB7=
    Set PB8=
    Set PB9=
    Set PB10=
    Set PB11=
    Set PB12=
 
Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Logan Varibles
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Username
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
REM    Set UN1=
REM    Set UN2=
REM    Set UN3=
REM    Set UN4=
REM    Set UN5=
REM    Set UN6=
REM    Set UN7=
REM    Set UN8=
REM    Set UN9=
REM    Set UN10=
REM    Set UN11=
REM    Set UN12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Password
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PS1=
    Set PS2=
    Set PS3=
    Set PS4=
    Set PS5=
    Set PS6=
    Set PS7=
    Set PS8=
    Set PS9=
    Set PS10=
    Set PS11=
    Set PS12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem PC Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set PN1=
    Set PN2=
    Set PN3=
    Set PN4=
    Set PN5=
    Set PN6=
    Set PN7=
    Set PN8=
    Set PN9=
    Set PN10=
    Set PN11=
    Set PN12=
 
  Rem ------ -------- -------- -------- -------- ------- -------- -------
  Rem Domain Name
  Rem ---------- -------- -------- -------- -------- ------- -------- ---
    Set DM1=
    Set DM2=
    Set DM3=
    Set DM4=
    Set DM5=
    Set DM6=
    Set DM7=
    Set DM8=
    Set DM9=
    Set DM10=
    Set DM11=
    Set DM12=
