Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Change Characters Assigned To Keys Thus Providing Detection Ability
Rem Using CHOICE.COM
Rem Up-´, Down-µ, Enter-¶, Escape-·, F10-¸, Left-¹, Del-º, Right-»
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Echo [224;72;"´"p
  Echo [224;80;"µ"p
  Echo [13;"¶"p
  Echo [27;"·"p
  Echo [0;68;"¸"p
  Echo [224;75;"¹"p
  Echo [224;83;"º"p
  Echo [224;77;"»"p
