Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Update Primary WINS
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set PW1=%1
  Set PW2=%2
  Set PW3=%3
  Set PW4=%4
  Set PW5=%5
  Set PW6=%6
  Set PW7=%7
  Set PW8=%8
  Set PW9=%9
  Shift
  Set PW10=%9
  Shift
  Set PW11=%9
  Shift
  Set PW12=%9
  Shift

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Update Secondary WINS
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set SW1=%9
  Shift
  Set SW2=%9
  Shift
  Set SW3=%9
  Shift
  Set SW4=%9
  Shift
  Set SW5=%9
  Shift
  Set SW6=%9
  Shift
  Set SW7=%9
  Shift
  Set SW8=%9
  Shift
  Set SW9=%9
  Shift
  Set SW10=%9
  Shift
  Set SW11=%9
  Shift
  Set SW12=%9
  Shift

Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Update Building
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Set BUILDING=%9
