Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Each Item
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call MENBUI04 ON 1
  Call MENBUI04 OFF 2
  Call MENBUI04 OFF 3
  Call MENBUI04 OFF 4
  Call MENBUI04 OFF 5
  Call MENBUI04 OFF 6
  Call MENBUI04 OFF 7
  Call MENBUI04 OFF 8
  Call MENBUI04 OFF 9
  Call MENBUI04 OFF 10
  Call MENBUI04 OFF 11
