Rem ------ -------- -------- -------- -------- ------- -------- -------
Rem Display Each Item
Rem ---------- -------- -------- -------- -------- ------- -------- ---
  Call MENBUI04 ERASE 1
  Call MENBUI04 ERASE 2
  Call MENBUI04 ERASE 3
  Call MENBUI04 ERASE 4
  Call MENBUI04 ERASE 5
  Call MENBUI04 ERASE 6
  Call MENBUI04 ERASE 7
  Call MENBUI04 ERASE 8
  Call MENBUI04 ERASE 9
  Call MENBUI04 ERASE 10
  Call MENBUI04 ERASE 11
